save_dir: "/home/pervinco/Models/detection"

epochs: 200
batch_size: 32

init_lr: 0.0001
use_scheduler: true
warmup_epochs: 100
max_lr: 0.001
min_lr: 0.00001

weight_decay: 0.0001

grid_size: 7
num_boxes: 2
