train: "/home/pervinco/DL-workspace/VISION/object_detection/YoloV3/data/train.txt"
valid: "/home/pervinco/DL-workspace/VISION/object_detection/YoloV3/data/2007_test.txt"
names:
  [
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    "tvmonitor",
  ]
