## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
save_dir: "/home/pervinco/Models/BKAI_IGH_NeoPolyp/TransResUNet"
pretrain_weight: ""

## backbone
backbone: "resnet152"

## hyp-params
mask_threshold: 50
img_size: 256
batch_size: 32
epochs: 500
basic_lr: 0.0001

loss_fn: "dice"
optimizer: "Adam"
betas: [0.9, 0.999]
momentum: 0.9

## class weights
use_weight: True
num_classes: 3

## lr scheduler
use_scheduler: True

onplateau: False
patience: 10

cosine_annealing: False
start_lr: 0.001
min_lr: 0.000001
decay_term: 20

one_cycle: True
max_lr: 0.01

## early-stop
early_stopping_patience: 100

## train-pred samples
num_pred_samples: 5
