## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
save_dir: "/home/pervinco/Models/BKAI_IGH_NeoPolyp/TransResUNet"
pretrain_weight: ""

## backbone
backbone: "resnet50"

## encoder layers
num_layers: 2

## hyp-params
epochs: 1000
img_size: 256
batch_size: 16

loss_fn: "dice"
optimizer: "Adam"
betas: [0.9, 0.999]
momentum: 0.9

## class weights
use_weight: False
num_classes: 3

## lr scheduler
use_scheduler: True
initial_lr: 0.0001
max_lr: 0.001
pct_start: 0.8

## early-stop
early_stopping_patience: 100

## train-pred samples
num_pred_samples: 5
