## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
save_dir: "/home/pervinco/Models/BKAI_IGH_NeoPolyp/TransResUNet"

## backbone
backbone: "resnet50"

## hyp-params
mask_threshold: 50
img_size: 256
batch_size: 32
epochs: 500
basic_lr: 0.0001

loss_fn: "dice"
optimizer: "Adam"
betas: [0.9, 0.999]
momentum: 0.9

## class weights
use_weight: False
num_classes: 3

## cosine annealing restart
cosine_annealing: True
start_lr: 0.0001
min_lr: 0.000001
decay_term: 80

## early-stop
early_stopping_patience: 50

## train-pred samples
num_pred_samples: 5

## normalize
means: [138.17342764808024, 91.28627298925218, 71.78929893564148]
stds: [75.50602558856306, 56.697154870570145, 47.498044858528985]
