## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
save_dir: "/home/pervinco/Models/BKAI_IGH_NeoPolyp/TransResUNet"
pretrain_weight: ""

## backbone
backbone: "resnet152"
num_layers: 12 ## encoder layers

## hyp-params
epochs: 500
img_size: 256
batch_size: 32
initial_lr: 0.0001
betas: [0.5, 0.99]
momentum: 0.9

## Loss func
num_classes: 3
crossentropy: True
give_penalty: False
penalty_factor: 2

## lr scheduler
scheduler: True
max_lr: 0.001
pct_start: 0.8

## early-stop
early_stopping_patience: 500

## pred samples
num_pred_samples: 5
