dataset: cifar100 # ["cifar10", "cifar100"]
dataset_dir: "/home/pervinco/Datasets"

model_type: ViT-L_32 # ["ViT-B_16", "ViT-B_32", "ViT-L_16", "ViT-L_32", "ViT-H_14"]
pretrained: "/home/pervinco/Models/checkpoint/imagenet21k/ViT-L_32.npz"
save_dir: "/home/pervinco/Models/ViT"

seed: 42
local_rank: -1

num_steps: 10000 # num_steps
img_size: 224
train_batch_size: 32
valid_batch_size: 16
valid_term: 100

learning_rate: 0.003
weight_decay: 0
decay_type: "cosine" # ["cosine", "linear"]
warmup_steps: 500 ## need to fix steps -> epoch
max_grad_norm: 1.0

gradient_accumulation_steps: 1