save_dir: "/home/pervinco/Models/yolov1"
pretrained: "/home/pervinco/Models/darknet53_best.pth.tar"

grid_size: 7
num_boxes: 2
num_classes: 20

threshold: 0.5
iou_threshold: 0.45

epochs: 300
batch_size: 32
img_size: 448

init_lr: 0.00001
weight_decay: 0.0001

use_scheduler: false
warmup_epochs: 100
max_lr: 0.001
min_lr: 0.00001
