data_dir: "/home/pervinco/Datasets/sports-image-classification"
save_dir: "/home/pervinco/Models/classification"

model_name: "efficientnet-b0"
pretrained: true

epochs: 200
batch_size: 128
img_size: 224

init_lr: 0.0001

use_scheduler: true
warmup_epochs: 100
max_lr: 0.001
min_lr: 0.00001

momentum: 0.9
weight_decay: 0.0001

valid_ratio: 0.2
